# Generated by Django 5.0.4 on 2024-05-26 10:48

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(height_field=100, null=True, upload_to=utils.utils.user_self_directory_path, width_field=100),
        ),
    ]
