# Generated by Django 5.0.4 on 2024-05-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
