# Generated by Django 5.0.4 on 2024-05-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_rename_user_userprofile_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
    ]
